version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    env_file: 
      - ./backend/.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - inet
    expose:
      - "3306" 


  redis:
    image: redis:latest
    restart: always
    container_name: redis_container
    networks:
      - inet
    expose:
      - "6379"

  backend:
    build: ./backend
    container_name: backend_container
    env_file: ./backend/.env
    depends_on:
      - db
      - redis
    ports:
      - "8000"
    networks:
      - inet

  frontend:
    build: ./frontend
    container_name: frontend_container
    env_file: ./frontend/.env
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./backend/media:/app/media
    networks:
      - inet

volumes:
  mysql_data:

networks:
  inet:
    driver: bridge
