# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: grafana-provisioning
#   namespace: monitoring
# data:
#   dashboards.yaml: |
#     apiVersion: 1
#     providers:
#       - name: 'default'
#         orgId: 1
#         folder: ''
#         type: file
#         # updateIntervalSeconds: 10
#         options:
#           path: /var/lib/grafana/dashboards
