apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:           # ✅ le volume est stocké sur ton PC (Minikube host)
    path: /mnt/data/media
  persistentVolumeReclaimPolicy: Retain