apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: freelance
type: Opaque
stringData:
  SECRET_KEY: "django-insecure-!+%py_&^4asv^f5_p@*=yyh*+%$8*$nlz^v7w0*)7sdv_05sp!"
  DB_PASSWORD: "2975"
  MYSQL_ROOT_PASSWORD: "faly09+/+"
  EMAIL_HOST_USER: "randriantsoafaly8@gmail.com"
  EMAIL_HOST_PASSWORD: "lnyb uwdj lzcx whkf"
  
