apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-json
data:
  config.json: |
    {
      "API_URL": "http://freelance.stage:30000",          
      "WEBSOCKET_API_URL": "ws://freelance.stage:30000"   
    }
