apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
        - name: wait-for-backend
          image: busybox:1.36
          command: ['sh', '-c', '
            echo "⏳ Waiting for backend...";
            until nc -z backend 8000; do
              echo "Backend not ready yet...";
              sleep 5;
            done;
            echo "✅ Backend ready!";
            
            echo "⏳ Waiting for Redis...";
            until nc -z redis 6379; do
              echo "Redis not ready yet...";
              sleep 5;
            done;
            echo "✅ Redis ready!";
          ']
      containers:
        - name: frontend
          image: faly9/freelance-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            # - name: frontend-config
            #   mountPath: /usr/share/nginx/html/config.json
            #   subPath: config.json
            - name: media-storage
              mountPath: /usr/share/nginx/html/media
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-nginx-config
        # - name: frontend-config
        #   configMap:
        #     name: frontend-config-json
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc
