apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config-json
data:
  config.json: |
    {
      "API_URL": "http://192.168.88.27:8000',   
      "WEBSOCKET_API_URL": "ws://192.168.88.27:8000'
    }
