apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  # ğŸŒ API accessible depuis un navigateur externe (ton hÃ´te Windows)
  VITE_API_URL: "http://192.168.88.245:30000"
  VITE_WS_URL: "ws://192.168.88.245:30000"

  # ğŸ³ API accessible depuis le cluster Kubernetes
  VITE_API_DOCKER: "http://backend:8000"
  VITE_WS_DOCKER: "ws://backend:8000"
