apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/faly9/FullStack_Freelance'
    targetRevision: HEAD
    path: k8s/apps
    directory:
      recurse: true
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: freelance
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

