apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: freelance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
        - name: mysqld-exporter
          image: prom/mysqld-exporter:latest
          ports:
            - containerPort: 9104
          env:
            - name: DATA_SOURCE_NAME
              value: "exporter:2975@(mysql:3306)/"
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/.my.cnf
              subPath: .my.cnf
      volumes:
        - name: mysql-config
          secret:
            secretName: mysqld-exporter-config
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqld-exporter-config
  namespace: freelance
type: Opaque
stringData:
  .my.cnf: |
    [client]
    user=exporter
    password=2975
    host=mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: freelance
  labels:
    app: mysqld-exporter
spec:
  selector:
    app: mysqld-exporter
  ports:
    - name: http
      port: 9104
      targetPort: 9104
      protocol: TCP
  type: ClusterIP
