# mysqld-exporter-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysqld-exporter-dsn
  namespace: freelance
type: Opaque
data:
  # La valeur du DSN doit être encodée en base64. 
  # Exemple: "exporter:votre_mot_de_passe_secret@tcp(mysql:3306)/" encodé en base64
  # Vous devriez utiliser la commande suivante pour l'encodage:
  # echo -n "exporter:votre_mot_de_passe_secret@tcp(mysql:3306)/" | base64
  DATA_SOURCE_NAME: ZXhwb3J0ZXI6Mjk3NUB0Y3AobXlzcWw6MzMwNikv

