# mysqld-exporter-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysqld-exporter-dsn
  namespace: freelance
type: Opaque
data:
  DATA_SOURCE_NAME: ZXhwb3J0ZXI6Mjk3NUB0Y3AobXlzcWw6MzMwNikv

