apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: freelance
spec:
  selector:
    app: mysqld-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9104
      targetPort: 9104
  type: ClusterIP
