# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: prometheus-kubelet
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: prometheus-kubelet
# rules:
#   - apiGroups: [""]
#     resources: ["nodes/metrics"]
#     verbs: ["get", "list", "watch"]
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: prometheus-kubelet
# subjects:
#   - kind: ServiceAccount
#     name: prometheus-kubelet
# roleRef:
#   kind: ClusterRole
#   name: prometheus-kubelet
#   apiGroup: rbac.authorization.k8s.io
