# mysqld-exporter-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqld-exporter-config
  namespace: freelance
data:
  # Ce fichier sera mont√© en tant que .my.cnf
  my.cnf: |
    [client]
    host=mysql
    user=exporter
    password=2975
    port=3306