apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: freelance
  labels:
    app: mysqld-exporter
spec:
  selector:
    app: mysqld-exporter
  ports:
    - name: http
      port: 9104
      targetPort: 9104
      protocol: TCP
  type: ClusterIP